version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every month
      interval: "monthly"

  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: "daily"
      time: "07:00"
      timezone: "Europe/Helsinki"
    open-pull-requests-limit: 30
